#!/bin/sh

SITE=http://download.sgjp.pl/morfeusz/
DUMPSDIR=$HOME/data/dumps
TEMPDIR=$DUMPSDIR/.tmp
LOGFILE=.sgjp_last_timestamp
LASTTS=
RET=0
WGETOPTS="--spider --recursive --level=1 --no-host-directories --cut-dirs=1 --directory-prefix=$TEMPDIR"

date

if [ -e "$DUMPSDIR/$LOGFILE" ]; then
  LASTTS=`cat $DUMPSDIR/$LOGFILE | head -n 1`
  echo "last timestamp: $LASTTS"
else
  echo "no logfile found: $DUMPSDIR/$LOGFILE"
fi

echo "fetching directory list from $SITE..."
wget --quiet $WGETOPTS $SITE

LASTDUMP=`find $TEMPDIR -type d | xargs -n 1 basename | grep "^[0-9]*$" | sort | tail -n 1`

if [ -n "$LASTDUMP" ]; then
  echo "latest dump: $LASTDUMP"

  if [ -z "$LASTTS" ] || [ "$LASTDUMP" -gt "$LASTTS" ]; then
    echo "downloading .tar.gz..."
    wget --no-verbose -P $DUMPSDIR ${SITE}/${LASTDUMP}/sgjp-${LASTDUMP}.tab.gz

    echo "decompressing archive..."
    gzip -df $DUMPSDIR/sgjp-${LASTDUMP}.tab.gz

    echo "converting Windows line endings to Unix..."
    # https://unix.stackexchange.com/a/208167
    sed -i '/\r/ s///g' $DUMPSDIR/sgjp-${LASTDUMP}.tab

    echo "removing older files..."
    find $DUMPSDIR/sgjp-*.tab -type f | head -n -1 | xargs rm -v -f --

    echo "updating log file..."
    echo "$LASTDUMP" > $DUMPSDIR/$LOGFILE
  else
    echo "not downloading, already have latest dump"
  fi
else
  echo "unable to parse last dump folder"
  RET=1
fi

rm -rf $TEMPDIR

return $RET
